// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGA0f85HfwXoTc0SuVv7sJGdYoSbtVbls',
    appId: '1:132674884689:web:448bf2beed40d7ea105470',
    messagingSenderId: '132674884689',
    projectId: 'ask-pro-f92d4',
    authDomain: 'ask-pro-f92d4.firebaseapp.com',
    storageBucket: 'ask-pro-f92d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnogECrMNyrLAdMzie4sqU8B24dZj9ip4',
    appId: '1:132674884689:android:0c6b6c5c2b1e5b43105470',
    messagingSenderId: '132674884689',
    projectId: 'ask-pro-f92d4',
    storageBucket: 'ask-pro-f92d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0lsnXfipGjfSWWVnfGSTx9-GV8NmMcM',
    appId: '1:132674884689:ios:032d16eb78a090d7105470',
    messagingSenderId: '132674884689',
    projectId: 'ask-pro-f92d4',
    storageBucket: 'ask-pro-f92d4.appspot.com',
    iosBundleId: 'com.example.askpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0lsnXfipGjfSWWVnfGSTx9-GV8NmMcM',
    appId: '1:132674884689:ios:bd01df438bae845c105470',
    messagingSenderId: '132674884689',
    projectId: 'ask-pro-f92d4',
    storageBucket: 'ask-pro-f92d4.appspot.com',
    iosBundleId: 'com.example.askpro.RunnerTests',
  );
}
